// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Author: Evan Spendlove (@evanSpendlove)

//
//The Targets proto defines the config for a Target.
//Targets are used by Hermes and Cloudprober to identify storage systems to monitor.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.4
// source: targets.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// TargetSystem is expected to be a storage system.
// It will stay constant until support for new storage systems is added.
type TargetsDef_TargetSystem int32

const (
	TargetsDef_GOOGLE_CLOUD_STORAGE TargetsDef_TargetSystem = 0
	TargetsDef_CEPH                 TargetsDef_TargetSystem = 1
)

// Enum value maps for TargetsDef_TargetSystem.
var (
	TargetsDef_TargetSystem_name = map[int32]string{
		0: "GOOGLE_CLOUD_STORAGE",
		1: "CEPH",
	}
	TargetsDef_TargetSystem_value = map[string]int32{
		"GOOGLE_CLOUD_STORAGE": 0,
		"CEPH":                 1,
	}
)

func (x TargetsDef_TargetSystem) Enum() *TargetsDef_TargetSystem {
	p := new(TargetsDef_TargetSystem)
	*p = x
	return p
}

func (x TargetsDef_TargetSystem) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetsDef_TargetSystem) Descriptor() protoreflect.EnumDescriptor {
	return file_targets_proto_enumTypes[0].Descriptor()
}

func (TargetsDef_TargetSystem) Type() protoreflect.EnumType {
	return &file_targets_proto_enumTypes[0]
}

func (x TargetsDef_TargetSystem) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TargetsDef_TargetSystem.Descriptor instead.
func (TargetsDef_TargetSystem) EnumDescriptor() ([]byte, []int) {
	return file_targets_proto_rawDescGZIP(), []int{0, 0}
}

// TODO(#30) Establish connection method for GCS and Ceph using Go libraries.
type TargetsDef_ConnectionType int32

const (
	TargetsDef_HTTP  TargetsDef_ConnectionType = 0
	TargetsDef_HTTPS TargetsDef_ConnectionType = 1
)

// Enum value maps for TargetsDef_ConnectionType.
var (
	TargetsDef_ConnectionType_name = map[int32]string{
		0: "HTTP",
		1: "HTTPS",
	}
	TargetsDef_ConnectionType_value = map[string]int32{
		"HTTP":  0,
		"HTTPS": 1,
	}
)

func (x TargetsDef_ConnectionType) Enum() *TargetsDef_ConnectionType {
	p := new(TargetsDef_ConnectionType)
	*p = x
	return p
}

func (x TargetsDef_ConnectionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetsDef_ConnectionType) Descriptor() protoreflect.EnumDescriptor {
	return file_targets_proto_enumTypes[1].Descriptor()
}

func (TargetsDef_ConnectionType) Type() protoreflect.EnumType {
	return &file_targets_proto_enumTypes[1]
}

func (x TargetsDef_ConnectionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TargetsDef_ConnectionType.Descriptor instead.
func (TargetsDef_ConnectionType) EnumDescriptor() ([]byte, []int) {
	return file_targets_proto_rawDescGZIP(), []int{0, 1}
}

// TargetsDef contains all of the metadata necessary for Hermes to establish a connection to a storage system.
// Every probe request will require one or more targets.
type TargetsDef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetSystem          TargetsDef_TargetSystem   `protobuf:"varint,1,opt,name=target_system,json=targetSystem,proto3,enum=hermes.TargetsDef_TargetSystem" json:"target_system,omitempty"`
	ConnectionType        TargetsDef_ConnectionType `protobuf:"varint,2,opt,name=connection_type,json=connectionType,proto3,enum=hermes.TargetsDef_ConnectionType" json:"connection_type,omitempty"`
	CephConnectionDetails *CephConnectionDetails    `protobuf:"bytes,3,opt,name=ceph_connection_details,json=cephConnectionDetails,proto3" json:"ceph_connection_details,omitempty"`
	TargetUrl             string                    `protobuf:"bytes,5,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`                                  // URL for connecting to the the API of the target storage system.
	TotalSpaceAllocated   int64                     `protobuf:"varint,4,opt,name=total_space_allocated,json=totalSpaceAllocated,proto3" json:"total_space_allocated,omitempty"` // in MBs.
}

func (x *TargetsDef) Reset() {
	*x = TargetsDef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_targets_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetsDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetsDef) ProtoMessage() {}

func (x *TargetsDef) ProtoReflect() protoreflect.Message {
	mi := &file_targets_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetsDef.ProtoReflect.Descriptor instead.
func (*TargetsDef) Descriptor() ([]byte, []int) {
	return file_targets_proto_rawDescGZIP(), []int{0}
}

func (x *TargetsDef) GetTargetSystem() TargetsDef_TargetSystem {
	if x != nil {
		return x.TargetSystem
	}
	return TargetsDef_GOOGLE_CLOUD_STORAGE
}

func (x *TargetsDef) GetConnectionType() TargetsDef_ConnectionType {
	if x != nil {
		return x.ConnectionType
	}
	return TargetsDef_HTTP
}

func (x *TargetsDef) GetCephConnectionDetails() *CephConnectionDetails {
	if x != nil {
		return x.CephConnectionDetails
	}
	return nil
}

func (x *TargetsDef) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *TargetsDef) GetTotalSpaceAllocated() int64 {
	if x != nil {
		return x.TotalSpaceAllocated
	}
	return 0
}

// REQUIRED, when using Ceph as the target system.
// Comparable functionality is handled in the Go client library for GCS.
type CephConnectionDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port int32 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"` // Port for connecting to Ceph S3 API
	// REQUIRED for Ceph S3 API
	// GCS uses service account credentials instead.
	ApiKey string `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
}

func (x *CephConnectionDetails) Reset() {
	*x = CephConnectionDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_targets_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CephConnectionDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CephConnectionDetails) ProtoMessage() {}

func (x *CephConnectionDetails) ProtoReflect() protoreflect.Message {
	mi := &file_targets_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CephConnectionDetails.ProtoReflect.Descriptor instead.
func (*CephConnectionDetails) Descriptor() ([]byte, []int) {
	return file_targets_proto_rawDescGZIP(), []int{1}
}

func (x *CephConnectionDetails) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CephConnectionDetails) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

// Targets allows the user to define multiple targets.
type Targets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Targets []*TargetsDef `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
}

func (x *Targets) Reset() {
	*x = Targets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_targets_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Targets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Targets) ProtoMessage() {}

func (x *Targets) ProtoReflect() protoreflect.Message {
	mi := &file_targets_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Targets.ProtoReflect.Descriptor instead.
func (*Targets) Descriptor() ([]byte, []int) {
	return file_targets_proto_rawDescGZIP(), []int{2}
}

func (x *Targets) GetTargets() []*TargetsDef {
	if x != nil {
		return x.Targets
	}
	return nil
}

var File_targets_proto protoreflect.FileDescriptor

var file_targets_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x22, 0xa3, 0x03, 0x0a, 0x0a, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x73, 0x44, 0x65, 0x66, 0x12, 0x44, 0x0a, 0x0d, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e,
	0x68, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x44, 0x65,
	0x66, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x52, 0x0c,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x4a, 0x0a, 0x0f,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x2e, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x44, 0x65, 0x66, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x55, 0x0a, 0x17, 0x63, 0x65, 0x70, 0x68,
	0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x68, 0x65, 0x72, 0x6d,
	0x65, 0x73, 0x2e, 0x43, 0x65, 0x70, 0x68, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x15, 0x63, 0x65, 0x70, 0x68, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12,
	0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x32,
	0x0a, 0x15, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x61, 0x6c,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x13, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x53, 0x70, 0x61, 0x63, 0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x65, 0x64, 0x22, 0x32, 0x0a, 0x0c, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x53, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x12, 0x18, 0x0a, 0x14, 0x47, 0x4f, 0x4f, 0x47, 0x4c, 0x45, 0x5f, 0x43, 0x4c, 0x4f,
	0x55, 0x44, 0x5f, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04,
	0x43, 0x45, 0x50, 0x48, 0x10, 0x01, 0x22, 0x25, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x54, 0x54, 0x50,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x54, 0x54, 0x50, 0x53, 0x10, 0x01, 0x22, 0x44, 0x0a,
	0x15, 0x43, 0x65, 0x70, 0x68, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x70,
	0x69, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69,
	0x4b, 0x65, 0x79, 0x22, 0x37, 0x0a, 0x07, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x12, 0x2c,
	0x0a, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73,
	0x44, 0x65, 0x66, 0x52, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x42, 0x35, 0x5a, 0x33,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x2f, 0x73, 0x74, 0x65, 0x70, 0x32, 0x32, 0x34,
	0x2d, 0x32, 0x30, 0x32, 0x30, 0x2f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_targets_proto_rawDescOnce sync.Once
	file_targets_proto_rawDescData = file_targets_proto_rawDesc
)

func file_targets_proto_rawDescGZIP() []byte {
	file_targets_proto_rawDescOnce.Do(func() {
		file_targets_proto_rawDescData = protoimpl.X.CompressGZIP(file_targets_proto_rawDescData)
	})
	return file_targets_proto_rawDescData
}

var file_targets_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_targets_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_targets_proto_goTypes = []interface{}{
	(TargetsDef_TargetSystem)(0),   // 0: hermes.TargetsDef.TargetSystem
	(TargetsDef_ConnectionType)(0), // 1: hermes.TargetsDef.ConnectionType
	(*TargetsDef)(nil),             // 2: hermes.TargetsDef
	(*CephConnectionDetails)(nil),  // 3: hermes.CephConnectionDetails
	(*Targets)(nil),                // 4: hermes.Targets
}
var file_targets_proto_depIdxs = []int32{
	0, // 0: hermes.TargetsDef.target_system:type_name -> hermes.TargetsDef.TargetSystem
	1, // 1: hermes.TargetsDef.connection_type:type_name -> hermes.TargetsDef.ConnectionType
	3, // 2: hermes.TargetsDef.ceph_connection_details:type_name -> hermes.CephConnectionDetails
	2, // 3: hermes.Targets.targets:type_name -> hermes.TargetsDef
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_targets_proto_init() }
func file_targets_proto_init() {
	if File_targets_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_targets_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TargetsDef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_targets_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CephConnectionDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_targets_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Targets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_targets_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_targets_proto_goTypes,
		DependencyIndexes: file_targets_proto_depIdxs,
		EnumInfos:         file_targets_proto_enumTypes,
		MessageInfos:      file_targets_proto_msgTypes,
	}.Build()
	File_targets_proto = out.File
	file_targets_proto_rawDesc = nil
	file_targets_proto_goTypes = nil
	file_targets_proto_depIdxs = nil
}
