// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// state_journal defines the structure that stores the state of Hermes.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.4
// source: github.com/googleinterns/step224-2020/hermes/proto/state_journal.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// FileOperation is used for recording the operation intent within the
// StateJournal of Hermes.
type Intent_FileOperation int32

const (
	Intent_FILE_OPERATION_UNSPECIFIED Intent_FileOperation = 0
	Intent_CREATE                     Intent_FileOperation = 1
	Intent_DELETE                     Intent_FileOperation = 2
)

// Enum value maps for Intent_FileOperation.
var (
	Intent_FileOperation_name = map[int32]string{
		0: "FILE_OPERATION_UNSPECIFIED",
		1: "CREATE",
		2: "DELETE",
	}
	Intent_FileOperation_value = map[string]int32{
		"FILE_OPERATION_UNSPECIFIED": 0,
		"CREATE":                     1,
		"DELETE":                     2,
	}
)

func (x Intent_FileOperation) Enum() *Intent_FileOperation {
	p := new(Intent_FileOperation)
	*p = x
	return p
}

func (x Intent_FileOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Intent_FileOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_enumTypes[0].Descriptor()
}

func (Intent_FileOperation) Type() protoreflect.EnumType {
	return &file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_enumTypes[0]
}

func (x Intent_FileOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Intent_FileOperation.Descriptor instead.
func (Intent_FileOperation) EnumDescriptor() ([]byte, []int) {
	return file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_rawDescGZIP(), []int{1, 0}
}

// StateJournal stores the state of Hermes in two parts:
// the next operation intent and a map of filenames.
type StateJournal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The intent stores the operation to be performed and the name of the file on
	// which the operation is to be performed.
	Intent *Intent `protobuf:"bytes,1,opt,name=intent,proto3" json:"intent,omitempty"`
	// The filenames map is a map of file IDs to filenames.
	// If an entry does not exist for a given ID, then the file does not exist.
	Filenames map[int32]string `protobuf:"bytes,2,rep,name=filenames,proto3" json:"filenames,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *StateJournal) Reset() {
	*x = StateJournal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateJournal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateJournal) ProtoMessage() {}

func (x *StateJournal) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateJournal.ProtoReflect.Descriptor instead.
func (*StateJournal) Descriptor() ([]byte, []int) {
	return file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_rawDescGZIP(), []int{0}
}

func (x *StateJournal) GetIntent() *Intent {
	if x != nil {
		return x.Intent
	}
	return nil
}

func (x *StateJournal) GetFilenames() map[int32]string {
	if x != nil {
		return x.Filenames
	}
	return nil
}

// Intent stores the next intended file operation of Hermes.
type Intent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileOperation Intent_FileOperation `protobuf:"varint,1,opt,name=fileOperation,proto3,enum=hermes.Intent_FileOperation" json:"fileOperation,omitempty"`
	Filename      string               `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (x *Intent) Reset() {
	*x = Intent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Intent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Intent) ProtoMessage() {}

func (x *Intent) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Intent.ProtoReflect.Descriptor instead.
func (*Intent) Descriptor() ([]byte, []int) {
	return file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_rawDescGZIP(), []int{1}
}

func (x *Intent) GetFileOperation() Intent_FileOperation {
	if x != nil {
		return x.FileOperation
	}
	return Intent_FILE_OPERATION_UNSPECIFIED
}

func (x *Intent) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

var File_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto protoreflect.FileDescriptor

var file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_rawDesc = []byte{
	0x0a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x2f, 0x73, 0x74, 0x65, 0x70, 0x32,
	0x32, 0x34, 0x2d, 0x32, 0x30, 0x32, 0x30, 0x2f, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x6a, 0x6f, 0x75, 0x72, 0x6e,
	0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x73,
	0x22, 0xb7, 0x01, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61,
	0x6c, 0x12, 0x26, 0x0a, 0x06, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x52, 0x06, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x41, 0x0a, 0x09, 0x66, 0x69, 0x6c,
	0x65, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x68,
	0x65, 0x72, 0x6d, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x75, 0x72, 0x6e,
	0x61, 0x6c, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x1a, 0x3c, 0x0a, 0x0e,
	0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xb1, 0x01, 0x0a, 0x06, 0x49,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x42, 0x0a, 0x0d, 0x66, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x68,
	0x65, 0x72, 0x6d, 0x65, 0x73, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x66, 0x69, 0x6c, 0x65,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x47, 0x0a, 0x0d, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x1a, 0x46, 0x49, 0x4c, 0x45, 0x5f, 0x4f,
	0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45,
	0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x42, 0x34,
	0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x2f, 0x73, 0x74, 0x65, 0x70, 0x32,
	0x32, 0x34, 0x2d, 0x32, 0x30, 0x32, 0x30, 0x2f, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_rawDescOnce sync.Once
	file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_rawDescData = file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_rawDesc
)

func file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_rawDescGZIP() []byte {
	file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_rawDescOnce.Do(func() {
		file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_rawDescData)
	})
	return file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_rawDescData
}

var file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_goTypes = []interface{}{
	(Intent_FileOperation)(0), // 0: hermes.Intent.FileOperation
	(*StateJournal)(nil),      // 1: hermes.StateJournal
	(*Intent)(nil),            // 2: hermes.Intent
	nil,                       // 3: hermes.StateJournal.FilenamesEntry
}
var file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_depIdxs = []int32{
	2, // 0: hermes.StateJournal.intent:type_name -> hermes.Intent
	3, // 1: hermes.StateJournal.filenames:type_name -> hermes.StateJournal.FilenamesEntry
	0, // 2: hermes.Intent.fileOperation:type_name -> hermes.Intent.FileOperation
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_init() }
func file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_init() {
	if File_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateJournal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Intent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_goTypes,
		DependencyIndexes: file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_depIdxs,
		EnumInfos:         file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_enumTypes,
		MessageInfos:      file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_msgTypes,
	}.Build()
	File_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto = out.File
	file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_rawDesc = nil
	file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_goTypes = nil
	file_github_com_googleinterns_step224_2020_hermes_proto_state_journal_proto_depIdxs = nil
}
