// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Author: Evan Spendlove (@evanSpendlove)
//
// The DeleteFileProbe proto describes the information necessary for a probe to delete a
// file in GCS.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.4
// source: github.com/googleinterns/step224-2020/gcs/deleteFile/proto/deleteFile.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	proto2 "github.com/google/cloudprober/probes/proto"
	proto1 "github.com/googleinterns/step224-2020/config/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// DeleteFileProbe describes the information necessary for a probe to delete a
// file in GCS.
type DeleteFileProbe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// REQUIRED
	// HermesProbeDef includes extra information, such as additional metrics, that
	// is not included in the config.proto supplied by Cloudprober.
	Probedef *proto1.HermesProbeDef `protobuf:"bytes,1,opt,name=probedef" json:"probedef,omitempty"`
	// REQUIRED
	// The name of the bucket that contains the object to be deleted.
	BucketName *string `protobuf:"bytes,2,opt,name=bucketName" json:"bucketName,omitempty"`
}

func (x *DeleteFileProbe) Reset() {
	*x = DeleteFileProbe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFileProbe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileProbe) ProtoMessage() {}

func (x *DeleteFileProbe) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileProbe.ProtoReflect.Descriptor instead.
func (*DeleteFileProbe) Descriptor() ([]byte, []int) {
	return file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteFileProbe) GetProbedef() *proto1.HermesProbeDef {
	if x != nil {
		return x.Probedef
	}
	return nil
}

func (x *DeleteFileProbe) GetBucketName() string {
	if x != nil && x.BucketName != nil {
		return *x.BucketName
	}
	return ""
}

var file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*proto2.ProbeDef)(nil),
		ExtensionType: (*DeleteFileProbe)(nil),
		Field:         220,
		Name:          "hermes.delete_file.DeleteFileProbe.delete_file_probe",
		Tag:           "bytes,220,opt,name=delete_file_probe",
		Filename:      "github.com/googleinterns/step224-2020/gcs/deleteFile/proto/deleteFile.proto",
	},
}

// Extension fields to proto2.ProbeDef.
var (
	// Extension code explanation:
	// 200-299 = Codes for GCS
	// 220-229 = Codes for deleting files in GCS
	//
	// optional hermes.delete_file.DeleteFileProbe delete_file_probe = 220;
	E_DeleteFileProbe_DeleteFileProbe = &file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_extTypes[0] // 200 because GCS, 20 because Delete probe
)

var File_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto protoreflect.FileDescriptor

var file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_rawDesc = []byte{
	0x0a, 0x4b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x2f, 0x73, 0x74, 0x65, 0x70, 0x32,
	0x32, 0x34, 0x2d, 0x32, 0x30, 0x32, 0x30, 0x2f, 0x67, 0x63, 0x73, 0x2f, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x68,
	0x65, 0x72, 0x6d, 0x65, 0x73, 0x2e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x66, 0x69, 0x6c,
	0x65, 0x1a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72,
	0x2f, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x3e, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x73, 0x2f, 0x73, 0x74, 0x65, 0x70, 0x32, 0x32, 0x34, 0x2d, 0x32, 0x30, 0x32,
	0x30, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x72, 0x6f, 0x62, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd5, 0x01, 0x0a, 0x0f, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x12, 0x32,
	0x0a, 0x08, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x64, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x2e, 0x48, 0x65, 0x72, 0x6d, 0x65, 0x73,
	0x50, 0x72, 0x6f, 0x62, 0x65, 0x44, 0x65, 0x66, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x64,
	0x65, 0x66, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x32, 0x6e, 0x0a, 0x11, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x12, 0x1c, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70,
	0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x6f,
	0x62, 0x65, 0x44, 0x65, 0x66, 0x18, 0xdc, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x68,
	0x65, 0x72, 0x6d, 0x65, 0x73, 0x2e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x66, 0x69, 0x6c,
	0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x62,
	0x65, 0x52, 0x0f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x72, 0x6f,
	0x62, 0x65, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x2f, 0x73,
	0x74, 0x65, 0x70, 0x32, 0x32, 0x34, 0x2d, 0x32, 0x30, 0x32, 0x30, 0x2f, 0x67, 0x63, 0x73, 0x2f,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_rawDescOnce sync.Once
	file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_rawDescData = file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_rawDesc
)

func file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_rawDescGZIP() []byte {
	file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_rawDescOnce.Do(func() {
		file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_rawDescData)
	})
	return file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_rawDescData
}

var file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_goTypes = []interface{}{
	(*DeleteFileProbe)(nil),       // 0: hermes.delete_file.DeleteFileProbe
	(*proto1.HermesProbeDef)(nil), // 1: hermes.HermesProbeDef
	(*proto2.ProbeDef)(nil),       // 2: cloudprober.probes.ProbeDef
}
var file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_depIdxs = []int32{
	1, // 0: hermes.delete_file.DeleteFileProbe.probedef:type_name -> hermes.HermesProbeDef
	2, // 1: hermes.delete_file.DeleteFileProbe.delete_file_probe:extendee -> cloudprober.probes.ProbeDef
	0, // 2: hermes.delete_file.DeleteFileProbe.delete_file_probe:type_name -> hermes.delete_file.DeleteFileProbe
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_init() }
func file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_init() {
	if File_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFileProbe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_goTypes,
		DependencyIndexes: file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_depIdxs,
		MessageInfos:      file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_msgTypes,
		ExtensionInfos:    file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_extTypes,
	}.Build()
	File_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto = out.File
	file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_rawDesc = nil
	file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_goTypes = nil
	file_github_com_googleinterns_step224_2020_gcs_deleteFile_proto_deleteFile_proto_depIdxs = nil
}
